project:
  type: book
  output-dir: docs
  
book:
  title: "RMCC Contracts Management"
  author: "Pablo Vivas"
  date: "9/22/2025"
  chapters:
    - index.qmd
    - 01-contracts.qmd
    - 02-projects.qmd
    - 03-qa.qmd

bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    - assets/theme.scss